spring.application.name=queueManeger

spring.data.mongodb.uri=mongodb://localhost:27017/sistema-fila
# Login do Atendente
spring.security.user.name=atendente
spring.security.user.password=senhaSegura123
spring.security.user.roles=ADMIN