spring.application.name=queueManager

# Pega a URL do ambiente ou usa localhost se não encontrar
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/sistema-fila}

# Configurações de Log (opcional, mas recomendado)
logging.level.root=INFO
logging.level.com.umari=DEBUG